const USER_STORAGE = "@marketspace:user" //CHAVE PARA ARMAZENAR O USUÁRIO
const AUTH_TOKEN_STORAGE = "@marketspace:token" //CHAVE PARA ARMAZENAR O TOKEN DO USUÁRIO

export { USER_STORAGE, AUTH_TOKEN_STORAGE };